version: "3"

services:
   node0:
      container_name: node0
      image: "augusteum/localnode"
      ports:
         - "26656-26657:26656-26657"
      environment:
         - ID=0
         - LOG=${LOG:-augusteum.log}
      volumes:
         - ./build:/augusteum:Z
      networks:
         localnet:
            ipv4_address: 192.167.10.2

   node1:
      container_name: node1
      image: "augusteum/localnode"
      ports:
         - "26659-26660:26656-26657"
      environment:
         - ID=1
         - LOG=${LOG:-augusteum.log}
      volumes:
         - ./build:/augusteum:Z
      networks:
         localnet:
            ipv4_address: 192.167.10.3

   node2:
      container_name: node2
      image: "augusteum/localnode"
      environment:
         - ID=2
         - LOG=${LOG:-augusteum.log}
      ports:
         - "26661-26662:26656-26657"
      volumes:
         - ./build:/augusteum:Z
      networks:
         localnet:
            ipv4_address: 192.167.10.4

   node3:
      container_name: node3
      image: "augusteum/localnode"
      environment:
         - ID=3
         - LOG=${LOG:-augusteum.log}
      ports:
         - "26663-26664:26656-26657"
      volumes:
         - ./build:/augusteum:Z
      networks:
         localnet:
            ipv4_address: 192.167.10.5

networks:
   localnet:
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 192.167.10.0/16
